[[redirects]]
  from = "https://edtest1.netlify.app/"
  to = "https://edtest1.netlify.app/ "
  force = false
  conditions = {Country =  ["US"]}
  
  [[redirects]]
  from = "https://edtest1.netlify.app/"
  to = "https://www.google.com/ "
  force = false

  
